"""
strategy.py — 2m Strict Strategy Engine
════════════════════════════════════════
Implements all 5 trigger rules from the task brief.
"""

import logging
from datetime import datetime, timezone
from dataclasses import dataclass
from typing import Optional

from config import (
    TIMING_MODULO, VOLUME_SURGE_MULTIPLIER, VOLUME_LOOKBACK,
    MIN_BODY_PCT, EMA_30M_PERIOD, EMA_1H_PERIOD,
    NY_SESSION_START_UTC, NY_SESSION_END_UTC,
)
from data_fetcher import compute_ema

logger = logging.getLogger("bt.strategy")


@dataclass
class Signal:
    """A trade signal generated by the 2m Strict strategy."""
    timestamp_ms: int          # candle open time
    signal_type: str           # "LONG" or "SHORT"
    candle_open: float
    candle_close: float
    candle_high: float
    candle_low: float
    candle_volume: float
    volume_ratio: float        # current_vol / avg_10
    body_pct: float            # body size as % of close
    ema_30m_20: float          # EMA value at signal time
    ema_1h_50: float           # EMA value at signal time
    is_ny_session: bool


class Strategy2mStrict:
    """
    2m Strict Strategy — 5 conditions must ALL be true:
    1. TIMING:   First 2m candle of each 5m window
    2. VOLUME:   Volume >= 200% of avg(10 previous candles)
    3. BODY:     Body >= 0.08% of close price
    4. DIRECTION: Green=LONG, Red=SHORT
    5. EMA:      LONG: price > 20EMA(30m) AND > 50EMA(1h)
                 SHORT: price < both EMAs
    """

    def __init__(self, candles_30m: list[dict], candles_1h: list[dict]):
        """Pre-compute EMAs from higher timeframe candles."""
        # Compute EMAs
        self.ema_30m_values = compute_ema(candles_30m, EMA_30M_PERIOD)
        self.ema_1h_values = compute_ema(candles_1h, EMA_1H_PERIOD)

        # Build lookup: timestamp_ms → EMA value
        # For each 2m candle, we use the LAST COMPLETED higher-TF candle's EMA
        self._ema_30m_lookup = {}
        for i, c in enumerate(candles_30m):
            self._ema_30m_lookup[c["t"]] = self.ema_30m_values[i]

        self._ema_1h_lookup = {}
        for i, c in enumerate(candles_1h):
            self._ema_1h_lookup[c["t"]] = self.ema_1h_values[i]

        # Sorted timestamps for bisect lookup
        self._ema_30m_times = sorted(self._ema_30m_lookup.keys())
        self._ema_1h_times = sorted(self._ema_1h_lookup.keys())

        logger.info(
            f"Strategy initialized: "
            f"30m EMA({EMA_30M_PERIOD}) = {len(self._ema_30m_times)} points, "
            f"1h EMA({EMA_1H_PERIOD}) = {len(self._ema_1h_times)} points"
        )

    def _get_ema_at(self, timestamp_ms: int, times: list, lookup: dict) -> Optional[float]:
        """Get the most recent EMA value at or before timestamp_ms."""
        import bisect
        idx = bisect.bisect_right(times, timestamp_ms) - 1
        if idx < 0:
            return None
        return lookup[times[idx]]

    def evaluate(self, candles_2m: list[dict], index: int) -> Optional[Signal]:
        """
        Evaluate the 2m candle at `index` against all 5 rules.
        Returns Signal if all pass, None otherwise.
        """
        if index < VOLUME_LOOKBACK:
            return None

        candle = candles_2m[index]
        open_time_ms = candle["t"]
        dt = datetime.fromtimestamp(open_time_ms / 1000, tz=timezone.utc)

        # ── Rule 1: TIMING — First 2m of 5m window ──
        if dt.minute % TIMING_MODULO != 0:
            return None

        # ── Rule 2: VOLUME SURGE — >= 200% of avg 10 ──
        prev_volumes = [candles_2m[index - j]["v"] for j in range(1, VOLUME_LOOKBACK + 1)]
        avg_vol = sum(prev_volumes) / len(prev_volumes) if prev_volumes else 0

        if avg_vol <= 0:
            return None

        vol_ratio = candle["v"] / avg_vol
        if vol_ratio < VOLUME_SURGE_MULTIPLIER:
            return None

        # ── Rule 3: FULL-BODIED — body >= 0.08% of close ──
        body = abs(candle["c"] - candle["o"])
        body_pct = body / candle["c"] if candle["c"] > 0 else 0

        if body_pct < MIN_BODY_PCT:
            return None

        # ── Rule 4: DIRECTION ──
        if candle["c"] > candle["o"]:
            direction = "LONG"
        elif candle["c"] < candle["o"]:
            direction = "SHORT"
        else:
            return None  # doji, skip

        # ── Rule 5: EMA TREND FILTER ──
        ema_30m = self._get_ema_at(open_time_ms, self._ema_30m_times, self._ema_30m_lookup)
        ema_1h = self._get_ema_at(open_time_ms, self._ema_1h_times, self._ema_1h_lookup)

        if ema_30m is None or ema_1h is None:
            return None  # not enough EMA data yet (warm-up)

        price = candle["c"]
        if direction == "LONG":
            if not (price > ema_30m and price > ema_1h):
                return None
        else:  # SHORT
            if not (price < ema_30m and price < ema_1h):
                return None

        # ── All 5 rules passed! Generate signal ──
        is_ny = NY_SESSION_START_UTC <= dt.hour < NY_SESSION_END_UTC

        return Signal(
            timestamp_ms=open_time_ms,
            signal_type=direction,
            candle_open=candle["o"],
            candle_close=candle["c"],
            candle_high=candle["h"],
            candle_low=candle["l"],
            candle_volume=candle["v"],
            volume_ratio=round(vol_ratio, 2),
            body_pct=round(body_pct, 6),
            ema_30m_20=round(ema_30m, 2),
            ema_1h_50=round(ema_1h, 2),
            is_ny_session=is_ny,
        )
